/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/weatherforecast': {
    get: operations['GetWeatherForecast']
  }
  '/companies': {
    get: operations['GetCompanies']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    CompanyDto: {
      /** Format: int32 */
      id?: number
      name?: string | null
      /** Format: date */
      creationDate?: string
      employees?: components['schemas']['EmployeeDto'][] | null
    }
    EmployeeDto: {
      /** Format: int32 */
      id?: number
      name?: string | null
    }
    WeatherForecast: {
      /** Format: date */
      date?: string
      /** Format: int32 */
      temperatureC?: number
      /** Format: int32 */
      temperatureF?: number
      summary?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  GetWeatherForecast: {
    parameters: {
      query: {
        num: number
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['WeatherForecast'][]
        }
      }
    }
  }
  GetCompanies: {
    parameters: {
      query: {
        num: number
        num2: number
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['CompanyDto'][]
        }
      }
      /** @description Not Found */
      404: {
        content: never
      }
    }
  }
}
